/*
 * Jpanel pou skopo exei na emfanizei stin MainFrame tis plirofories kathe antikimenou 
 * Periexei kai Button gia "xtypima" stin dimoprasia
 */

/*
 * ItemPanel.java
 *
 * Created on Feb 3, 2013, 7:07:34 PM
 */

package engtest;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author CFatseas, GPanetsos
 */
public class ItemPanel extends javax.swing.JPanel  {
    private PreparedStatement preparedStatement;

    /** 
     * Kataskeuastis me orisma ena antikoimeno "Item"
     * pou periexei tis plirofories pou tha emfanistoun 
     */
    public ItemPanel(Item item) {
        initComponents();
        title.setText(item.getTitle());
        user.setText(item.getUser());
        category.setText(item.getCategory());
        description.setText(item.getDescription());
        time.setText(Integer.toString(item.getTime()));
        price.setText(Integer.toString(item.getPrice()));
        ImageIcon img = new ImageIcon(Utilities.scaleImage(item.getImage(),136,136));
        iconLabel.setIcon(img);
        id = item.getId();
        newPrice = item.getPrice();

    }

    /*
     * Methodoi get/set
     */
    public ItemPanel() {
        initComponents();
    }

    public void setTitle(String title){
        this.title.setText(title);
    }

    public void setUser(String user){
        this.user.setText(user);
    }

    public void setCategory(String category){
        this.category.setText(category);
    }

    public void setDescription(String description){
        this.description.setText(description);
    }

    public void setTime(int time){
        this.time.setText(Integer.toString(time));
    }

    public void setPrice(int price){
        this.price.setText(Integer.toString(price));
    }

    public void setImg(Icon img){
        iconLabel.setIcon(img);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JLabel();
        user = new javax.swing.JLabel();
        category = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        iconLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        description = new javax.swing.JTextPane();
        time = new javax.swing.JLabel();
        price = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(700, 164));

        title.setFont(new java.awt.Font("Monotype Sorts", 0, 14)); // NOI18N
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("title");

        user.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        user.setText("jLabel2");

        category.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        category.setText("jLabel3");

        jPanel1.setPreferredSize(new java.awt.Dimension(136, 136));

        iconLabel.setPreferredSize(new java.awt.Dimension(136, 136));

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(iconLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(iconLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        );

        description.setEditable(false);
        description.setAutoscrolls(false);
        jScrollPane2.setViewportView(description);

        time.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        time.setText("jLabel5");

        price.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        price.setText("jLabel6");

        jButton1.setText("Place bid");
        jButton1.setAlignmentY(0.0F);
        jButton1.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bidBtn(evt);
            }
        });

        jLabel1.setText("Category :");

        jLabel2.setText("Price € :");

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        jLabel3.setText("Highest bidder:");

        jLabel4.setText("Remaning days :");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(title, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 379, Short.MAX_VALUE)
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createSequentialGroup()
                                .add(jLabel4)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                .add(time, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 63, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(layout.createSequentialGroup()
                                .add(jLabel3)
                                .add(18, 18, 18)
                                .add(user, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 110, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                            .add(jLabel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(jLabel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createSequentialGroup()
                                .add(price)
                                .add(52, 52, 52))
                            .add(category, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)))
                    .add(jButton1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 350, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jScrollPane2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 183, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 136, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(23, 23, 23)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(layout.createSequentialGroup()
                        .add(title)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel3)
                            .add(user, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 16, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(category)
                            .add(jLabel1))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel4)
                            .add(time)
                            .add(price)
                            .add(jLabel2))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(jButton1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 54, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jPanel1, 0, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jScrollPane2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        title.getAccessibleContext().setAccessibleName("");
    }// </editor-fold>//GEN-END:initComponents

    /*
     * Enimerwsi tis DB gia tin nea timi (+1) kai ton neo prosorino nikiti
     */
    private void bidBtn(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bidBtn
        if (MainFrame.username==null) {
            JOptionPane.showMessageDialog(null, "Can't buy yet!", "Login Please", JOptionPane.INFORMATION_MESSAGE);
        }else {
            if (MainFrame.username.equals(user.getText())){
                JOptionPane.showMessageDialog(null, "Already Highest Bidder !!", "Warning", JOptionPane.INFORMATION_MESSAGE);
            }else {
                try {
                    newPrice += 1;
                    String sql = "update Items set User=? ,Price=? where ID=?";
                    Connection conn = DbConn.connect();
                    preparedStatement = conn.prepareStatement(sql);
                    preparedStatement.setString(1, MainFrame.username);
                    preparedStatement.setInt(2, newPrice);
                    preparedStatement.setInt(3, id);
                    preparedStatement.execute();
                    DbConn.disconnect(conn);
                    user.setText(MainFrame.username);
                    price.setText(Integer.toString(newPrice));
                } catch (SQLException ex) {
                    Logger.getLogger(ItemPanel.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_bidBtn

    private int newPrice;
    private int id;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel category;
    private javax.swing.JTextPane description;
    private javax.swing.JLabel iconLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel price;
    private javax.swing.JLabel time;
    private javax.swing.JLabel title;
    private javax.swing.JLabel user;
    // End of variables declaration//GEN-END:variables

}
